// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function Elevate():Promise<string>;

export function FixConfigPermissions(arg1:string):Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetOS():Promise<string>;

export function GetStartError():Promise<string>;

export function GetVersion():Promise<string>;

export function IsDNSRunning():Promise<boolean>;

export function OpenFileDialog(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;
