// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Elevate() {
  return window['go']['main']['App']['Elevate']();
}

export function FixConfigPermissions(arg1) {
  return window['go']['main']['App']['FixConfigPermissions'](arg1);
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function GetStartError() {
  return window['go']['main']['App']['GetStartError']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsDNSRunning() {
  return window['go']['main']['App']['IsDNSRunning']();
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}
